### ISSUE TITLE
Toolchains with recent versions of gcc

### ISSUE THREAD

**Issue by michaelrodgers80** [mzpqnxow/realtek-mips-sdks#2]
I'm trying to compile a C++ project that is using a modern version of C++ for a Lexra processor.
The latest realtek SDK that's been uploaded to this repository (`4.4.7`) has a version of `gcc` that's too old.

Do you know where can I find newer versions of rsdk that may have a more up-to-date gcc?
Thank you.

**Comment by mzpqnxow** [comment]
Sorry, I didn't see your post!

I think your best bet (aside from Google) is to contact Realtek :/
