### ISSUE TITLE
@mzpqnxow

### ISSUE THREAD

**Issue by rjtlrlxjfzz** [mzpqnxow/realtek-mips-sdks#4]
@mzpqnxow 
Hello. Is there a way to contact you? Such as email, Discord, Skype, or Telegram.

**Comment by mzpqnxow** [comment]
You can probably use github @ <my github username> .com

**Comment by rjtlrlxjfzz** [comment]
Do you have a skype or discord or telegram account?
I would like to pay and have the masscan code modified

**Comment by mzpqnxow** [comment]
> Do you have a skype or discord or telegram account?
> I would like to pay and have the masscan code modified
> Message ID: ***@***.***>
> 

Sorry, I don't do paid work and unfortunately am too busy even if I did

Thank you for the offer though!
